### ISSUE TITLE
opendkim-genkey fails following instructions in README

### ISSUE THREAD

**Issue by javier-godoy** [instrumentisto/opendkim-docker-image#1]
I've just installed a container based on instrumentisto/opendkim:alpine (Alpine 3.12) and opendkim-genkey failed with the following message.
```
opendkim-genkey: generating private key
opendkim-genkey: openssl exited with status %d
```

It happens that opendkim-genkey requires `openssl`, which is not installed. In another machine I had an instance of opendkim:alpine based on Alpine 3.10 where openssl was a softlink to libressl (I can't recall if it was modified in the container or not)

Please either update that in the image, or mention it in https://github.com/instrumentisto/opendkim-docker-image#keys-generation.

**Comment by tyranron** [comment]
@javier-godoy as we're using Alpine version, we haven't run into this.

The OpenSSL is definitely shoud be added to the image. Also, a regression test for that should be added.

PR is welcome.

**Comment by javier-godoy** [comment]
@tyranron I just added `RUN ln -s /usr/bin/libressl /usr/bin/openssl` in my Dockerfile and opendkim-genkey succeeded.
a
