### ISSUE TITLE
Provide 2.11.x builds?

### ISSUE THREAD

**Issue by tomsommer** [instrumentisto/opendkim-docker-image#2]
Would it be possible to also provide the OpenDKIM 2.11.x builds?

**Comment by tyranron** [comment]
@tomsommer I don't see them on the official download page, neither in the official repo in SourceForge.

**Comment by tomsommer** [comment]
https://github.com/trusteddomainproject/OpenDKIM/releases

**Comment by tyranron** [comment]
@tomsommer thanks for the link, but we're not going to support beta versions. Once it hits stable, we wil definitely release them.
