### ISSUE TITLE
/sbin/syslogd: No such file or directory

### ISSUE THREAD

**Issue by KevinBLT** [instrumentisto/opendkim-docker-image#6]
The command `exec /sbin/syslogd -n` is not working for me. 
I have to do `cp /usr/sbin/syslogd /sbin/syslogd` inside the container to see logs.

Did the path change?

**Comment by tyranron** [comment]
@KevinBLT I guess, yes. And we don't have a regression test for whether `syslogd` runs OK after container start. Would love to see a PR.

**Comment by tyranron** [comment]
Released as [`2.10.3-r23`](https://github.com/instrumentisto/opendkim-docker-image/releases/tag/2.10.3-r23).

**Comment by secretofthesteel** [comment]
Thanx for patching this issue!
